# Site settings
title: Contacto
description: > # this means to ignore newlines until "baseurl:"
  Es una prueba de un JamStack creado con generador de sitios estáticos llamado Jekyll
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jamstackjekyll.netlify.app/" # the base hostname & protocol for your site
github_username:  TripleYei

# Build settings
markdown: kramdown
